---
- name: cPanel managed VM deployment
  hosts: all
  remote_user: root

  tasks:
  - name: update all existing packages
    yum:
      name: "*"
      state: latest
      update_cache: yes
  
  - name: disalbed firewalld/iptables
    systemd:
      name: iptables
      state: stopped
      enabled: no
  
  - name: Ensure wget is installed
    dnf:
      name: wget
      state: present
      

