---
- name: cPanel managed VM deployment
  hosts: all
  remote_user: root

  tasks:
  - name: update all existing packages
    yum:
      name: "*"
      state: latest
      update_cache: yes
  
  - name: disalbed firewalld/iptables
    systemd:
      name: iptables
      state: stopped
      enabled: no
  
  - name: Ensure wget is installed
    yum:
      name: curl
      state: present
      
  - name: Download cPanel installer
    ansible.builtin.get_url:
      url: https://securedownloads.cpanel.net/latest
      dest: /home/latest
      mode: '0755'

  - name: Run cPanel installer
    ansible.builtin.shell: |
      sh /home/latest
    args:
      chdir: /home      

